---
title: "Rprog Assignment 3"
author: "tedscott"
date: "December 31, 2015"
output: html_document
---

Hospital data analysis

```{r}
# check out the data
setwd("C:/GIT/datascience/Rprogramming/ProgAssignment3")
outcome <- read.csv("outcome-of-care-measures.csv", colClasses = "character")
View(outcome)

# histogram of mortality by heart attack (column 11)
hist(as.numeric(outcome$Hospital.30.Day.Death..Mortality..Rates.from.Heart.Attack))


```

Finding best hospital in the state (part 2)

```{r}
# to put in best.R
best <- function(state, outcome) {
  ## Read outcome data, change "Not Available" to NA
  outcomes <- read.csv("outcome-of-care-measures.csv", na.strings = "Not Available", stringsAsFactors=FALSE) 
  # create vector of valid outcomes
  validOutcomes <- c("heart attack", "pneumonia", "heart failure")
  
  ## Check that state and outcome args are valid
  if (!(state %in% outcomes$State)) {stop("invalid state")}
  else if (!(outcome %in% validOutcomes)) {stop("invalid outcome")}
  
  ## Return hospital name in that state with lowest 30-day death
  ## rate
  
  # heart attack outcome
  if (outcome == "heart attack") {
    
    # subset to the two columns we need, only rows with no NAs
    resultSet <- subset(outcomes, outcomes$State == state, select = c(Hospital.Name, Hospital.30.Day.Death..Mortality..Rates.from.Heart.Attack))
    good <- complete.cases(resultSet)
    resultSet <- resultSet[good, ]
    
    # now sort the results, first ascending by outcome, then hospital name
    sortedResults <- resultSet[with(resultSet, order(Hospital.30.Day.Death..Mortality..Rates.from.Heart.Attack, Hospital.Name)), ]
    
  }
  else if (outcome == "pneumonia") {
    # subset to the two columns we need, only rows with no NAs
    resultSet <- subset(outcomes, outcomes$State == state, select = c(Hospital.Name, Hospital.30.Day.Death..Mortality..Rates.from.Pneumonia))
    good <- complete.cases(resultSet)
    resultSet <- resultSet[good, ]
    
    # now sort the results, first ascending by outcome, then hospital name
    sortedResults <- resultSet[with(resultSet, order(Hospital.30.Day.Death..Mortality..Rates.from.Pneumonia, Hospital.Name)), ]
  }
  else if (outcome == "heart failure") {
    # subset to the two columns we need, only rows with no NAs
    resultSet <- subset(outcomes, outcomes$State == state, select = c(Hospital.Name, Hospital.30.Day.Death..Mortality..Rates.from.Heart.Failure))
    good <- complete.cases(resultSet)
    resultSet <- resultSet[good, ]
    
    # now sort the results, first ascending by outcome, then hospital name
    sortedResults <- resultSet[with(resultSet, order(Hospital.30.Day.Death..Mortality..Rates.from.Heart.Failure, Hospital.Name)), ]
  }
  
  # return best hospital
  #head(sortedResults)
  sortedResults$Hospital.Name[1]
}


```

Hospital Rankings part 3

```{r}

rankhospital <- function(state, outcome, num = "best") {
## Read outcome data, change "Not Available" to NA
  outcomes <- read.csv("outcome-of-care-measures.csv", na.strings = "Not Available", stringsAsFactors=FALSE) 
  # create vector of valid outcomes
  validOutcomes <- c("heart attack", "pneumonia", "heart failure")
  
  ## Check that state and outcome args are valid
  if (!(state %in% outcomes$State)) {stop("invalid state")}
  else if (!(outcome %in% validOutcomes)) {stop("invalid outcome")}
  
  
## Return hospital name in that state with the given rank
## 30-day death rate
  # heart attack outcome
  if (outcome == "heart attack") {
    
    # subset to the two columns we need, only rows with no NAs
    resultSet <- subset(outcomes, outcomes$State == state, select = c(Hospital.Name, Hospital.30.Day.Death..Mortality..Rates.from.Heart.Attack))
    good <- complete.cases(resultSet)
    resultSet <- resultSet[good, ]
    
    # now sort the results, first ascending by outcome, then hospital name
    sortedResults <- resultSet[with(resultSet, order(Hospital.30.Day.Death..Mortality..Rates.from.Heart.Attack, Hospital.Name)), ]
    
  }
  else if (outcome == "pneumonia") {
    # subset to the two columns we need, only rows with no NAs
    resultSet <- subset(outcomes, outcomes$State == state, select = c(Hospital.Name, Hospital.30.Day.Death..Mortality..Rates.from.Pneumonia))
    good <- complete.cases(resultSet)
    resultSet <- resultSet[good, ]
    
    # now sort the results, first ascending by outcome, then hospital name
    sortedResults <- resultSet[with(resultSet, order(Hospital.30.Day.Death..Mortality..Rates.from.Pneumonia, Hospital.Name)), ]
  }
  else if (outcome == "heart failure") {
    # subset to the two columns we need, only rows with no NAs
    resultSet <- subset(outcomes, outcomes$State == state, select = c(Hospital.Name, Hospital.30.Day.Death..Mortality..Rates.from.Heart.Failure))
    good <- complete.cases(resultSet)
    resultSet <- resultSet[good, ]
    
    # now sort the results, first ascending by outcome, then hospital name
    sortedResults <- resultSet[with(resultSet, order(Hospital.30.Day.Death..Mortality..Rates.from.Heart.Failure, Hospital.Name)), ]
  }
  
  # return value based on num argument
  if (num == "best") sortedResults$Hospital.Name[1]
  else if (num == "worst") sortedResults$Hospital.Name[nrow(sortedResults)]
  else sortedResults$Hospital.Name[num]
}


```

Part 4 - return a DF of the hospitals by state of a given rank for a given outcome

and don't use rankhospital for some reason

```{r}
#install.packages("dplyr")
#library(dplyr)
rankall <- function(outcome, num = "best") {
## Read outcome data, change "Not Available" to NA
  fullFile <- read.csv("outcome-of-care-measures.csv", na.strings = "Not Available", stringsAsFactors=FALSE) 
  # create vector of valid outcomes
  validOutcomes <- c("heart attack", "pneumonia", "heart failure")
  
  ## Check that state and outcome args are valid
  if (!(outcome %in% validOutcomes)) {stop("invalid outcome")}
  
  # reduce data set to columns of interest
  outcomes <- subset(fullFile, select = c(Hospital.Name, State, Hospital.30.Day.Death..Mortality..Rates.from.Heart.Attack, Hospital.30.Day.Death..Mortality..Rates.from.Heart.Failure, Hospital.30.Day.Death..Mortality..Rates.from.Pneumonia))
  names(outcomes) <- c("hospital", "state", "heart_attack", "heart_failure", "pneumonia")
  #View(outcomes)

  ## For each state, find the hospital of the given rank
  if (outcome == "heart attack") {
  
    # subset to the three columns we need, only rows with no NAs
    resultSet <- subset(outcomes, select = c(hospital, state, heart_attack))
    sortedResults <- resultSet[with(resultSet, order(state, heart_attack, hospital)), ]
    #View(sortedResults)
    if(num=="best") {
      sortedResults <- sortedResults %>%
        group_by(state) %>% 
        select(hospital, state) %>%
        slice(1)
    }
    else if(num=="worst") {
      sortedResults <- sortedResults %>%
        group_by(state) %>% 
        select(hospital, state) %>%
        slice(n())
    }
    else {
      sortedResults <- sortedResults %>%
        group_by(state) %>% 
        select(hospital, state) %>%
        slice(num)
    }
    
    # return the final DF
    sortedResults
  }
  
  else if (outcome == "heart failure") {
  
    # subset to the three columns we need, only rows with no NAs
    resultSet <- subset(outcomes, select = c(hospital, state, heart_failure))
    sortedResults <- resultSet[with(resultSet, order(state, heart_failure, hospital)), ]
    #View(sortedResults)
    if(num=="best") {
      sortedResults <- sortedResults %>%
        group_by(state) %>% 
        select(hospital, state) %>%
        slice(1)
    }
    else if(num=="worst") {
      sortedResults <- sortedResults %>%
        group_by(state) %>% 
        select(hospital, state) %>%
        slice(n())
    }
    else {
      sortedResults <- sortedResults %>%
        group_by(state) %>% 
        select(hospital, state) %>%
        slice(num)
    }
    
    # return the final DF
    sortedResults
  }
  else if (outcome == "pneumonia") {
  
    # subset to the three columns we need, only rows with no NAs
    resultSet <- subset(outcomes, select = c(hospital, state, pneumonia))
    sortedResults <- resultSet[with(resultSet, order(state, pneumonia, hospital)), ]
    #View(sortedResults)
    
    if(num=="best") {
      sortedResults <- sortedResults %>%
        group_by(state) %>% 
        select(hospital, state) %>%
        slice(1)
    }
    else if(num=="worst") {
      sortedResults <- sortedResults %>%
        group_by(state) %>% 
        select(hospital, state) %>%
        slice(n())
    }
    else {
      sortedResults <- sortedResults %>%
        group_by(state) %>% 
        select(hospital, state) %>%
        slice(num)
    }
    
    # return the final DF
    sortedResults
  }
}




```

