---
title: "HDF5"
author: "tedscott"
date: "December 19, 2015"
output: html_document
---

Working with HDF5 (Heirarchical Data Format for large data sets)
http://www.hdfgroup.org

Sort of like a DB in a file


```{r}
# need bioconductor package
source("http://bioconductor.org/biocLite.R")
biocLite("rhdf5")

# create a file of type hdf5
library(rhdf5)
created <- h5createFile("example.h5")
created

# create groups
created = h5createGroup("example.h5","foo")
created = h5createGroup("example.h5","baa")
created = h5createGroup("example.h5","foo/foobaa")

# see what groups we have made
h5ls("example.h5")

# write to groups and make some data sets
A <- matrix(1:10, nrow = 5, ncol = 2)
h5write(A, "example.h5","foo/A")
B = array(seq(0.1,2.0,by=0.1),dim=c(5,2,2))
attr(B, "scale") <-  "liter"
h5write(B, "example.h5","foo/foobaa/B")
h5ls("example.h5")

# write a dataset to the top level group
df=data.frame(1L:5L, seq(0,1,length.out=5), c("ab","cde","fghi","a","s"), stringsAsFactors = FALSE)
h5write(df, "example.h5","df")
h5ls("example.h5")

# OK, how about reading data?
readA <- h5read("example.h5","foo/A")
readB <- h5read("example.h5","foo/foobaa/B")
readDF <- h5read("example.h5","df")
readA

# can work with chunks
# write to first 3 row, in first column
h5write(c(12,13,14),"example.h5","foo/A",index=list(1:3,1))
h5read("example.h5","foo/A")




```

You can also embed plots, for example:

```{r, echo=FALSE}
plot(cars)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
