---
title: "Using Web APIs"
author: "tedscott"
date: "December 19, 2015"
output: html_document
---

Using Web APIs

Twitter

```{r}
# went to dev.twitter.com/apps and made an app to get auth tokens
# https://apps.twitter.com/app/9264166 is my app
library(base64enc)
myapp <- oauth_app("twitter", key="O2l9IBSYRrSeFT8nmQCPmyK5A", secret="NxfCFSsR9qipcy1wJnaTjtaLwiYw3qS8zxu6qQUZDhTOMObiKD")

sig=sign_oauth1.0(myapp, token="838185444-5SoyUu1kDBt9Yrar3ZDCeKSrXwFws6pcyLUFf4Sv", token_secret="ex0AJDP6kilqVSrJJd6tQ65zDa15byct0LczphVt6rE7d")
homeTL <- GET("https://api.twitter.com/1.1/statuses/home_timeline.json", sig)

# how did we know which API to use?
# twitter dev api documentation
#https://dev.twitter.com/docs/api/1.1/get/search/tweets
#https://dev.twitter.com/docs/api/1.1/get/statuses/home_timeline
#https://dev.twitter.com/docs/api/1.1/overview


library(jsonlite)
#use content function to extract json from homeTL
json1=content(homeTL)

# use jsonlite's fromJSON to extract contents
# of first tweet on my timeline
json2=jsonlite::fromJSON(toJSON(json1))
json2[1,1:4]
```

How about the GitHub API?

```{r}
# follow tutorial at 
# https://github.com/hadley/httr/blob/master/demo/oauth2-github.r
library(httpuv)

# Find OAuth settings for github:
# http://developer.github.com/v3/oauth/
oauth_endpoints("github")

# made an app at https://github.com/settings/applications/278277
GitHubApp <- oauth_app("github", key="4e84f1419585f28d78fc", secret="c6f333279e9396da3a055a51edec694c3847a76c")

# Get OAuth credentials
github_token <- oauth2.0_token(oauth_endpoints("github"), GitHubApp)

# Use API
gtoken <- config(token = github_token)
req <- GET("https://api.github.com/users/jtleek/repos", gtoken)
stop_for_status(req)
jsonContent <- content(req)
json2 <- jsonlite::fromJSON(toJSON(jsonContent))

# what are the field names?
names(json2)

# get the created date for the datasharing repo
json2$created_at[json2$name=="datasharing"]

```

