---
title: "Rprog Loop Functions"
author: "tedscott"
date: "December 22, 2015"
output: html_document
---

Week 3 - Loop Functions (lapply sapply apply tapply mapply split)

```{r}
# lapply - what goes in might not be a list, but it will be coerced into a list
# with as.list (giving an error if it fails)
# it always returns a list
(x <- list(a=1:5, b=rnorm(10)))
lapply(x, mean)

# generate four random uniform distributions
# first is length 1, last is length 4
# last two args are passed to runif as the min and max values
x <- 1:4
lapply(x, runif, min = 0, max = 10)

# can make use of anonymous or lambda functions
# to extract the first column of each of the matricies in
# a list of matricies
x <- list(a=matrix(1:4, 2, 2), b=matrix(1:6, 3, 2))
lapply(x, function(elt) elt[, 1])


# sapply tries to simply the result into a vector if possible
# or a matrix if the result is a list of vectors of the same length
# unless it can't, and then you get a list like lapply
(x <- list(a=1:5, b=rnorm(10), c=rnorm(20,1)))
sapply(x, mean)

# apply is used to evaluate a function of the margins of an array
# e.g. to do something over the rows or columns of a matrix
# not faster than a for loop, but is only one line

# 20 rows, 10 columns
x <- matrix(rnorm(200),20,10) 

# apply the mean to all the columns (dimension 2), get 10 results as a vector
apply(x, 2, mean) 

# apply the mean to all of the rows (dimension 1), get 20 results as a vector
apply(x, 1, mean)

# there are shortcut functions for the above and sums that are optimized
rowSums(x) # same as apply(x, 1, sum)
rowMeans(x) # same as apply(x, 1, mean)
colSums(x) # same as apply(x, 2, sum)
colMeans(x) # same as apply(x, 2, mean)

# 25% and 75% quantiles of the rows of a matrix
apply(x, 1, quantile, probs=c(0.25, 0.75))

# mapply takes multiple list arguments and applies the function to 
# all the elements of the lists in parallel

# here are two ways to make two lists of four lists
# first set of arguments is the 1-4 in the first arguments to the list func
# second set of arguments is the 4-1 in the second args to the list func
list(rep(1,4), rep(2,3), rep(3,2), rep(4,1))
mapply(rep, 1:4, 4:1) 


# tapply applies a function over subsets of a vector
# e.g. a vector where the first 50 elements are men and 2nd 50 are women
# the second arg to tapply is an index which is a factor (or is coerced)

# vector with three groups in it
x <- c(rnorm(10), runif(10), rnorm(10,1))
       
# create three groups of factors with gl() function
f <- gl(3,10)
f

tapply(x, f, mean)


# split()
# split takes a vector or other object and splits into groups based on a factor variable or list of factors
str(split)

# vector with three groups in it
x <- c(rnorm(10), runif(10), rnorm(10,1))
       
# create three groups of factors with gl() function
f <- gl(3,10)

# split x by factor f - get a list back with the original vector
# split into 3 groups
split(x, f)

# split followed by lapply - get means of the three groups from above
lapply(split(x,f), mean)

# use split to calculate mean in each month of airquality dataset
library(datasets)
head(airquality)

# split by month
# month is not factor by is coerced by split
s <- split(airquality, airquality$Month) 

# generate means of each of these three columns using lapply
lapply(s, function(x) colMeans(x[, c("Ozone", "Solar.R", "Temp")]))

# nicer output using sapply, fix NAs
sapply(s, function(x) colMeans(x[, c("Ozone", "Solar.R", "Temp")], na.rm=TRUE))


# splitting on more than one level!
# e.g. have gender (1 or 2) and race in a data set
x <- rnorm(n=10)
f1 <- gl(2,5) # two groups, five in each, represents gender
f2 <- gl(5,2) # five groups, 2 in each, represents race

# use interaction() to create the 2x5=10 combinations
interaction(f1, f2)

# split will automatically do the interaction for us if we pass in a list
# note that some are empty since the combination doesn't exist
# interesting to use str() here - makes it print out nicely
str(split(x, list(f1, f2)))

# drop the empty ones
str(split(x, list(f1, f2), drop = TRUE))

```

You can also embed plots, for example:

```{r, echo=FALSE}
plot(cars)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
