---
title: "not sure yet"
author: "tedscott"
date: "December 28, 2015"
output: html_document
---

Simulation

```{r}
# generate random numbers

# always set the seed with a number for reproducability
set.seed(5)

# rnorm generates random normal variates with a given mean and sd
rnorm(10, 0, 1)

# dnorm evaulate the normal prob density with a given
# mean/sd at a point or vector of points
dnorm()

# pnorm evaluate the cumulative distribution func for a normal distribution
# probability of getting x<=2 for a normal dist with mean=0, sd=1
pnorm(2, mean=0, sd=1)

# qnorm is for quantiles

# rpois generate random Poisson variates with a given rate
# 10 poisson randoms with a rate of 1 (mean = rate)
rpois(10,1) 

# ppois probability of getting a value of x with a given rate
# Pr(x <= 4 with rate 2)
ppois(4,2)



```

Simulate linear models

```{r}
# how to simulate
# y = B0 + B1*x + epsilon
# where epsilon is normally dist (mean=0, sd=2)
# and x is normally dist (mean=0, sd=1)
# B0 = 0.5
# B1 = 2

set.seed(20)
x <- rnorm(100)
e <- rnorm(100, 0, 2)
y <- 0.5 + 2 * x + e
summary(y)
plot(x, y)

# what if x is binary?
set.seed(10)
x <- rbinom(100, 1, 0.5)
e <- rnorm(100, 0, 2)
y <- 0.5 + 2 * x + e
summary(y)
plot(x, y)

# how about a more generalized linear model with
# a poisson distribution?
# y = poisson(mu)
# log(mu) = B0 + B1*x
# B0 = 0.5, B1 = 0.3
set.seed(1)
x <- rnorm(100)
log.mu <- 0.5 + 0.3 * x
y <-  rpois(100, exp(log.mu))
summary(y)
plot(x, y)


```

Random Sampling

```{r}
# sample function draws randomly from a given input set
# default for replacement is FALSE
set.seed(1)

# sample 4 numbers from 1 - 10
sample(1:10, 4)

# permutation
# get random order of the input set of the same size
sample(1:10)

# with replacement means we get duplicate values, sometimes
sample(1:10, replace = TRUE)


```

